### ISSUE TITLE
index.html - Create the overall HTML page and the navbar/footer

### ISSUE THREAD

**Issue by cjustice10** [cjustice10/Snowcast#2]

**Comment by patau** [comment]
Added:
Bootstrap header
Sticky footer

The signup/login links need to be messed with - they should only show up once.
The links are ui-sref, but the signup page has no .state in .js, so there's a console error when you click on it.
Ui-view should be working correctly. Emphasis on _should_. It probably works.
Should the large "snowcast" lead to the home page?
